//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/Input/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""FPSController"",
            ""id"": ""16e312a5-8d72-42ab-ad60-a87d71ed9447"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""331495d7-4fcc-49d1-829f-823af91d50fa"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""f7603440-74ae-46e2-9c73-d3e37f507414"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""4a424e2b-7fbe-49b9-ba8d-4d8468b2e5de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""KeyBoard"",
                    ""id"": ""2ea2c95c-0376-49d1-bf1a-a35d52e0adea"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6d35ed1d-ce46-4329-a53a-5da4d121c567"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ddec7ebb-4842-44d1-8bcc-e89ad201a9b0"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""23da9d56-ba63-4f32-9144-bbaead244758"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""bdda4e26-507a-46d1-b7c6-26072b9fa8f2"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b0f50e89-723b-47ca-bd2b-1bda0c7554d4"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ae252d7-4be0-40fc-8012-b321e38a7ac8"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd4495e7-8a5b-4f5d-b40f-b04277b05d05"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c227ed4-85dd-457b-a5ba-1a7616bf6e84"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f208c638-e7da-4804-82a1-e5a248130922"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""HackerController"",
            ""id"": ""149470da-7395-40c0-81e0-d5ceb4750f35"",
            ""actions"": [
                {
                    ""name"": ""Increment"",
                    ""type"": ""Button"",
                    ""id"": ""8eea24cc-65bc-4d5a-b1c5-b882748c9cb5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Decrement"",
                    ""type"": ""Button"",
                    ""id"": ""c067800b-d7b0-46ec-86cd-a71e5b824e09"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""106a1ba1-9faa-45cb-8816-88582459e82f"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Increment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78b7bc1f-acd7-4d02-9546-b88b0962187e"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Increment"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6dccec6e-81dd-45cd-a52f-bf7d9e1db03b"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Decrement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""173e08c3-506d-4441-aa1d-333a1269585e"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Decrement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // FPSController
        m_FPSController = asset.FindActionMap("FPSController", throwIfNotFound: true);
        m_FPSController_Move = m_FPSController.FindAction("Move", throwIfNotFound: true);
        m_FPSController_Look = m_FPSController.FindAction("Look", throwIfNotFound: true);
        m_FPSController_Interact = m_FPSController.FindAction("Interact", throwIfNotFound: true);
        // HackerController
        m_HackerController = asset.FindActionMap("HackerController", throwIfNotFound: true);
        m_HackerController_Increment = m_HackerController.FindAction("Increment", throwIfNotFound: true);
        m_HackerController_Decrement = m_HackerController.FindAction("Decrement", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // FPSController
    private readonly InputActionMap m_FPSController;
    private IFPSControllerActions m_FPSControllerActionsCallbackInterface;
    private readonly InputAction m_FPSController_Move;
    private readonly InputAction m_FPSController_Look;
    private readonly InputAction m_FPSController_Interact;
    public struct FPSControllerActions
    {
        private @PlayerInput m_Wrapper;
        public FPSControllerActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_FPSController_Move;
        public InputAction @Look => m_Wrapper.m_FPSController_Look;
        public InputAction @Interact => m_Wrapper.m_FPSController_Interact;
        public InputActionMap Get() { return m_Wrapper.m_FPSController; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FPSControllerActions set) { return set.Get(); }
        public void SetCallbacks(IFPSControllerActions instance)
        {
            if (m_Wrapper.m_FPSControllerActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_FPSControllerActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_FPSControllerActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_FPSControllerActionsCallbackInterface.OnMove;
                @Look.started -= m_Wrapper.m_FPSControllerActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_FPSControllerActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_FPSControllerActionsCallbackInterface.OnLook;
                @Interact.started -= m_Wrapper.m_FPSControllerActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_FPSControllerActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_FPSControllerActionsCallbackInterface.OnInteract;
            }
            m_Wrapper.m_FPSControllerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
            }
        }
    }
    public FPSControllerActions @FPSController => new FPSControllerActions(this);

    // HackerController
    private readonly InputActionMap m_HackerController;
    private IHackerControllerActions m_HackerControllerActionsCallbackInterface;
    private readonly InputAction m_HackerController_Increment;
    private readonly InputAction m_HackerController_Decrement;
    public struct HackerControllerActions
    {
        private @PlayerInput m_Wrapper;
        public HackerControllerActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Increment => m_Wrapper.m_HackerController_Increment;
        public InputAction @Decrement => m_Wrapper.m_HackerController_Decrement;
        public InputActionMap Get() { return m_Wrapper.m_HackerController; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(HackerControllerActions set) { return set.Get(); }
        public void SetCallbacks(IHackerControllerActions instance)
        {
            if (m_Wrapper.m_HackerControllerActionsCallbackInterface != null)
            {
                @Increment.started -= m_Wrapper.m_HackerControllerActionsCallbackInterface.OnIncrement;
                @Increment.performed -= m_Wrapper.m_HackerControllerActionsCallbackInterface.OnIncrement;
                @Increment.canceled -= m_Wrapper.m_HackerControllerActionsCallbackInterface.OnIncrement;
                @Decrement.started -= m_Wrapper.m_HackerControllerActionsCallbackInterface.OnDecrement;
                @Decrement.performed -= m_Wrapper.m_HackerControllerActionsCallbackInterface.OnDecrement;
                @Decrement.canceled -= m_Wrapper.m_HackerControllerActionsCallbackInterface.OnDecrement;
            }
            m_Wrapper.m_HackerControllerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Increment.started += instance.OnIncrement;
                @Increment.performed += instance.OnIncrement;
                @Increment.canceled += instance.OnIncrement;
                @Decrement.started += instance.OnDecrement;
                @Decrement.performed += instance.OnDecrement;
                @Decrement.canceled += instance.OnDecrement;
            }
        }
    }
    public HackerControllerActions @HackerController => new HackerControllerActions(this);
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    public interface IFPSControllerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
    }
    public interface IHackerControllerActions
    {
        void OnIncrement(InputAction.CallbackContext context);
        void OnDecrement(InputAction.CallbackContext context);
    }
}
